#!/bin/bash

. gt-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing gt-utils" >&2
  exit 1
fi

function showHelp
{
cat <<DOCSTRING
Usage: $(basename "$0") PRESET [REPONAME]

This command clones a git repository in the Current Working Directory (CWD).

'$(basename "$0")' performs the following actions:

1.  If the CWD is already under git version control, this script
    will abort.

2.  If the CWD is not empty, this script will abort.

3.  If the optional argument REPONAME is specified,
    this is used as the repository name. Otherwise
    the name of the CWD is used.

4.  The full location of the repository is determined based
    on PRESET and the repository name.
    For instructions on how to create and use presets, see the
    comments preceding the function called 'loadPreset' in the
    file 'gt-utils'.

5.  The repository is cloned in the CWD.

See also: the function 'loadPreset' in 'gt-utils'
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#


# 1.
if isInGit; then
    exitWith 1 "Error: The current working directory ( '$PWD' ) is already under git version control."
fi


# 2.
if ! isEmptyDir "$(pwd)"; then
    exitWith 1 "Error: The current working directory ( '$PWD' ) is not empty"
fi


# 3.
repoName=${2:-$(basename $(pwd))}


# 4.
loadPreset $1

# 5.
git clone "$(remoteRepoUrl "$repoName")" .
exitOnError "'git clone "$(remoteRepoUrl "$repoName")" .' returned an error."
