#!/bin/bash

. gt-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing gt-utils" >&2
  exit 1
fi

function showHelp
{
cat <<DOCSTRING
Usage: $(basename "$0") PRESET REPONAME [DIRNAME]

This command clones a git repository.

'$(basename "$0")' performs the following actions:

1.  DIRNAME is the destination directory. If not specified, then
    ./REPONAME is taken as DIRNAME.

2.  If DIRNAME exists:

    2.1  If DIRNAME is already under git version control,
         this script will abort.

    2.2  Otherwise, a warning is given that DIRNAME already exists,
         asking for the user's confirmation to continue.

3.  The full location of the remote repository is determined based
    on PRESET and the repository name.
    For instructions on how to create and use presets, see the
    comments preceding the function called 'loadPreset' in the
    file 'gt-utils'.

4.  The repository is cloned in DIRNAME.

5.  The DIRNAME-local properties:
        git config user.name
        git config user.email
    are set to their respective values as (and if) found in the preset
    file.

See also: the function 'loadPreset' in 'gt-utils'
DOCSTRING
}

checkForHelp $1
minNumArgs 2 $#


# 1.
preset="$1"
try test -n "$preset"

repoName="$2"
try test -n "$repoName"

dirName="${3:-"$repoName"}"
try test -n "$dirName"


# 2.
if [ -d "$dirName" ]; then

    # 2.1
    if isInGit; then
        exitWith 1 "Error: The directory '$dirName' ) is already under git version control."
    fi

    # 2.2
    echo -e "$(fg16 7)WARNING! The directory '$dirName' exists.$(fg0)"
    askUser "Do you want to continue [y/N]?" y n ci
    if [ "$?" -ne "0" ]; then
        exit
    fi

fi


# 3.
loadPreset "$preset"


# 4.
try git clone "$(remoteRepoUrl "$repoName")" "$dirName"
try cd "$dirName"


# 5.
test -n "$username" && try git config user.name "$username"
test -n "$useremail" && try git config user.email "$useremail"

# Clear status code
exit 0
