#!/bin/bash

. gt-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing gt-utils" >&2
  exit 1
fi

function showHelp
{
cat <<DOCSTRING
Usage: $(basename "$0") [-A] [MSG]

'$(basename "$0")' performs the following actions:

1   If the CWD is not under version control
    with git, this script will abort.

2.  Look for a file named 'precommit' in the
    Current Working Directory (CWD) and run ('source') it,
    if found.

3.  If the option "-A" is passed, all files in the git
    working tree are added to the index before comitting.
    Not recommended!

4.  The files are committed with commit message "MSG". If no
    argument is given, the commit message must be typed into
    a text editor that will open automatically.

See also: 'gtnew', 'gtclone'
DOCSTRING
}

checkForHelp $1

# 1.
if ! isInGit; then
    exitWith 1 "Error: the current working directory ( '$PWD' ) is not under git version control."
fi


# 2.
cd $(getToplevel)
if [ -f "./precommit" ]; then
    try . ./precommit
fi


#3.  Run the script 'clean-this' in your CWD.
#clean-this
#exitOnError "The script 'clean-this' returned an error."


# 3.
addAll=false
commitMsg=

function handleOptionalArgument
{
    if [ -n "$1" ]; then

        if [ "$1" == "-A" ]; then
            addAll=true
        else
            commitMsg="$1"
        fi

    fi
}

handleOptionalArgument "$1"
handleOptionalArgument "$2"

if "$addAll"; then
    try git add -A
fi


# 4.
if [ -n "$commitMsg" ]; then
    try git commit -m "$commitMsg"
else
    try git commit
fi
