#!/bin/bash

. gt-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing gt-utils" >&2
  exit 1
fi

function showHelp
{
cat <<DOCSTRING
Usage: $(basename "$0") TAGNAME

This command tags the commit referenced by HEAD and pushes the tag to the remote origin.

'$(basename "$0")' performs the following actions:

1.  The script aborts if:
        1.1. the Current Working Directory (CWD) is not under version control with git
        1.2. the git working tree has no remote upstream branch
        1.3. there are uncommited changes in the git working tree
        1.4. some commits are not yet pushed to the remote origin

2.  An annotated tag is created with the name 'TAGNAME'. The tag message is also set to TAGNAME.

3.  All tags that are not yet on the remote origin are pushed there.
DOCSTRING
}

minNumArgs 1 $#
checkForHelp $1

# 1.
    # 1.1
    if ! isInGit; then
        exitWith 1 "Error: the current working directory ( '$PWD' ) is not under git version control."
    fi

    # 1.2
    if ! hasUpstream; then
        exitWith 1 "Error: the git working tree has no remote upstream branch."
    fi

    # 1.3
    if hasUncommittedChanges; then
        exitWith 1 "Error: The git working tree has uncommitted changes."
    fi

    # 1.4
    if hasUnPushedCommits; then
        exitWith 1 "Error: The git working tree has un-pushed commits"
    fi


# 2.
tagname="$1"
git tag -a $tagname -m "$tagname"
exitOnError "'git tag -a $tagname -m "$tagname"' returned an error."


# 3.
if hasUpstream; then
    git push origin --tags
    exitOnError "'git push origin --tags' returned an error."
fi
