#!/bin/bash

# Github-specific code

require curl

####################################
#
# Create a remote repository
#
# createRemoteRepo REPONAME
#
function createRemoteRepo
{
    # TODO : outer single-quotes => inner un-escaped double-quotes?
    # --> s-qs escape variable substitution too
    # outer double-quotes? => inner un-escaped single-quotes?
    # --> inner s-qs don't escape variable substitution

#    repoName="$1"

    if [ -z "$1" ]; then
        exitWith 1 "Error: remoteRepoUrl : missing operand"
    fi

    curl -u "$username" "$apiurl/user/repos" -d "{\"name\": \"$1\", \"description\": \"Description goes here\", \"private\": false, \"has_issues\": true, \"has_downloads\": true, \"has_wiki\": false}"
}

####################################
#
# Prints full URL to remote repository on stdout
#
# remoteRepoUrl REPONAME
#
function remoteRepoUrl
{
    if [ -z "$1" ]; then
        exitWith 1 "Error: remoteRepoUrl : missing operand"
    fi

    echo "$repourl/$username/$1.git"
}
