#!/bin/bash

# Github-specific code

require curl

####################################
#
# Create a remote repository
#
# createRemoteRepo REPONAME
#
function createRemoteRepo
{
    if [ -z "$1" ]; then
        exitWith 1 "Error: remoteRepoUrl : missing operand"
    fi

    curl -u "$username" -X POST "$apiurl/user/repos" -d @- <<EOF
    {
        "name": "$1",
        "description": "Description goes here",
        "private": false,
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": false
    }
EOF
}

####################################
#
# Prints full URL to remote repository on stdout
#
# remoteRepoUrl REPONAME
#
function remoteRepoUrl
{
    if [ -z "$1" ]; then
        exitWith 1 "Error: remoteRepoUrl : missing operand"
    fi

    echo "$repourl/$username/$1.git"
}
