#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

# local-specific code

####################################
#
# Create a remote repository
#
# createRemoteRepo REPONAME
#
function createRemoteRepo
{
    if [ -d "$url/$1" ]; then
        errcho "The directory '$url/$1' already exists."
        false
    fi

    try mkdir -p "$url/$1"
    try pushd "$url/$1" > /dev/null
    try git init --bare
    try popd > /dev/null
}

####################################
#
# Prints the full URL to a remote repository on stdout
#
# remoteRepoUrl REPONAME
#
function remoteRepoUrl
{
    if [ -z "$1" ]; then
        exitWith 1 "Error: remoteRepoUrl : missing operand"
    fi

    echo "$url/$1"
}
